---
- name: "Stop nginx"
  service:
    become: true 
    name: nginx
    state: stopped

- name: "Start nginx"
  become: true 
  service: 
    name: nginx
    state: started

- name: "End msg"
  debug:
    msg: "Application deploy√© avec success"
...